In [6]:
from wandb_utils import find_best_run, calculate_mean_values, calculate_group_scores

In [7]:
# group_names_old_split = [
#     "last_bc",
#     "last_dqn",
#     "last_cql",
#     "last_sac",
#     "last_min",
#     "last_var",
#     "last_rem",
#     "first_bootstrapping_0.5",
#     "random_runs_diversification_seeds_90_0.2",
#     "random_runs_random_priors_seeds_90_0.2",
# ]

group_names_baselines = [
    "random_runs_bc_seeds",
    "random_runs_dqn_seeds",
    "random_runs_cql_seeds",
    "random_runs_dsac_seeds",
]

# proper_names = [
#     "Base Model",
#     "Ensemble Minimum",
#     "Ensemble Mean",
#     "Deep Ensembles/LCB",
#     "Bootstrapped Ensembles",
#     "Random Priors",
#     "Similarity Penalty I",
#     "Similarity Penalty II old",
#     # "Similarity Penalty II new"
# ]

group_names_dqn = [
    "random_runs_dqn_seeds",
    "random_runs_min_seeds",
    "beta_zero_dqn",
    "random_runs_var_seeds",
    "random_runs_bootstrapping_seeds",
    "random_runs_priors_seeds",
    "random_runs_div_seeds",
    "actual_similarity_penalty_theta_0_03",
    # "actual_similarity_penalty_theta_second"
]

group_names_dsac = [
    "random_runs_dsac_seeds_var",
    "first_policy_ensemble",
    "first_policy_ensemble_div",
]

In [9]:
calculate_mean_values(group_names_dsac, n_included_runs=20, n_finish=121, baseline_idx=0, originality=True, paired=False)

random_runs_dsac_seeds_var
first_policy_ensemble
first_policy_ensemble_div

,Group Name,Mean Seq Reward,Std Seq Reward,Mean Originality Score,P value,T stat,Significance
0,random_runs_dsac_seeds_var,0.951,0.013,0.99835,1.000000,0.000000,ns
1,first_policy_ensemble,0.963,0.005,0.99975,0.100735,-2.062642,ns
2,first_policy_ensemble_div,0.963,0.003,0.99925,0.019769,-2.714480,*

In [5]:
calculate_mean_values(group_names_dqn, n_included_runs=20, n_finish=101, baseline_idx=0, originality=True, paired=True)

random_runs_dqn_seeds
random_runs_min_seeds
beta_zero_dqn
random_runs_var_seeds
random_runs_bootstrapping_seeds
random_runs_priors_seeds
random_runs_div_seeds
actual_similarity_penalty_theta_0_03

,Group Name,Mean Seq Reward,Std Seq Reward,Mean Originality Score,P value,T stat,Significance
0,random_runs_dqn_seeds,0.902,0.036,0.955,NaN,NaN,ns
1,random_runs_min_seeds,0.924,0.026,0.950,0.157255,-1.542875,ns
2,beta_zero_dqn,0.943,0.028,0.980,0.033529,-2.506025,*
3,random_runs_var_seeds,0.941,0.029,0.965,0.026336,-2.653246,*
4,random_runs_bootstrapping_seeds,0.921,0.037,0.955,0.239485,-1.259635,ns
5,random_runs_priors_seeds,0.921,0.069,0.995,0.495605,-0.710140,ns
6,random_runs_div_seeds,0.954,0.021,0.990,0.010871,-3.197696,*
7,actual_similarity_penalty_theta_0_03,0.967,0.012,0.975,0.000237,-5.873780,***