In [1]:
from wandb_utils import find_best_run, calculate_mean_values, calculate_group_scores

In [2]:
# group_names_old_split = [
#     "last_bc",
#     "last_dqn",
#     "last_cql",
#     "last_sac",
#     "last_min",
#     "last_var",
#     "last_rem",
#     "first_bootstrapping_0.5",
#     "random_runs_diversification_seeds_90_0.2",
#     "random_runs_random_priors_seeds_90_0.2",
# ]

group_names_baselines = [
    "random_runs_bc_seeds",
    "random_runs_dqn_seeds",
    "random_runs_cql_seeds",
    "random_runs_dsac_seeds",
]

proper_names = [
    "Base Model",
    "Ensemble Minimum",
    "Ensemble Mean",
    "Deep Ensembles/LCB",
    "Bootstrapped Ensembles",
    "Random Priors",
    "Similarity Penalty I",
    "Similarity Penalty II"
]

group_names_dqn = [
    "random_runs_dqn_seeds",
    "random_runs_min_seeds",
    "beta_zero_dqn",
    "random_runs_var_seeds",
    "random_runs_bootstrapping_seeds",
    "random_runs_priors_seeds",
    "random_runs_div_seeds",
    "theta_0_01_div",
]

group_names_dsac = [
    "random_runs_dsac_seeds",
    "random_runs_dsac_seeds_min",
    "correlation_runs",
    "random_runs_dsac_seeds_var",
    "random_runs_dsac_seeds_bootstrapping",
    "random_runs_dsac_seeds_prior",
    "random_runs_dsac_seeds_div",
    "theta_0_1_div_sac"
]

In [3]:
all_values = calculate_mean_values(group_names_dqn, n_included_runs=50, n_finish=151, baseline_idx=0, originality=True)
all_values["proper_names"] = proper_names
all_values

random_runs_dqn_seeds
random_runs_min_seeds
beta_zero_dqn
random_runs_var_seeds
random_runs_bootstrapping_seeds
random_runs_priors_seeds
random_runs_div_seeds
theta_0_01_div

,Group Name,Mean Seq Reward,Std Seq Reward,Mean Originality Score,P value,T stat,Significance,proper_names
0,random_runs_dqn_seeds,0.902,0.035,0.952000,1.000000,0.000000,ns,Base Model
1,random_runs_min_seeds,0.923,0.025,0.932000,0.138641,-1.557865,ns,Ensemble Minimum
2,beta_zero_dqn,0.945,0.022,0.914000,0.004170,-3.372943,**,Ensemble Mean
3,random_runs_var_seeds,0.942,0.028,0.900000,0.010454,-2.872528,*,Deep Ensembles/LCB
4,random_runs_bootstrapping_seeds,0.927,0.036,0.951020,0.121794,-1.623884,ns,Bootstrapped Ensembles
5,random_runs_priors_seeds,0.914,0.088,0.986000,0.681236,-0.421160,ns,Random Priors
6,random_runs_div_seeds,0.944,0.030,0.969388,0.010286,-2.871645,*,Similarity Penalty I
7,theta_0_01_div,0.955,0.014,0.987755,0.000732,-4.497354,***,Similarity Penalty II

In [4]:
all_values = calculate_mean_values(group_names_dsac, n_included_runs=50, n_finish=151, baseline_idx=0, originality=True)
all_values["proper_names"] = proper_names
all_values

random_runs_dsac_seeds
random_runs_dsac_seeds_min
correlation_runs
random_runs_dsac_seeds_var
random_runs_dsac_seeds_bootstrapping
random_runs_dsac_seeds_prior
random_runs_dsac_seeds_div
theta_0_1_div_sac

,Group Name,Mean Seq Reward,Std Seq Reward,Mean Originality Score,P value,T stat,Significance,proper_names
0,random_runs_dsac_seeds,0.926,0.025,0.871429,1.000000,0.000000,ns,Base Model
1,random_runs_dsac_seeds_min,0.931,0.030,0.999020,0.727555,-0.354043,ns,Ensemble Minimum
2,correlation_runs,0.945,0.022,0.912245,0.085849,-1.818629,ns,Ensemble Mean
3,random_runs_dsac_seeds_var,0.951,0.012,0.998327,0.012915,-2.878891,*,Deep Ensembles/LCB
4,random_runs_dsac_seeds_bootstrapping,0.938,0.021,0.998959,0.276534,-1.123333,ns,Bootstrapped Ensembles
5,random_runs_dsac_seeds_prior,0.942,0.022,0.999837,0.149070,-1.508506,ns,Random Priors
6,random_runs_dsac_seeds_div,0.951,0.008,0.998245,0.011415,-3.043590,*,Similarity Penalty I
7,theta_0_1_div_sac,0.955,0.005,0.998163,0.005000,-3.593122,**,Similarity Penalty II